server:
  port: 8761

spring:
  application:
    name: zyz-eureka-server


# eureka集群相互通信时，既是服务端也是客户端
eureka:
  instance:
    hostname: zyz-eureka-server-1 # 当前eureka实例的主机名
  client:
    service-url:
      defaultZone: http://zyz-eureka-server-2:8762/eureka
    register-with-eureka: true
    fetch-registry: true