server:
  port: 8093
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: zyz-service-autodeliver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: fb1ea0fa-5af3-4a22-8bec-d3d93e574117

    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        # sentinel默认通信端口 dashboard中的限流规则通过此端口传递进来
        port: 8719

      datasource:
        flow: # 流控规则
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}-flow-rules
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow # 类型来⾃RuleType类

        degrade:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}-degrade-rules
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: degrade # 类型来⾃RuleType类

dubbo:
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: zyz-service-resume

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


