server:
  port: 9001
spring:
  application:
    name: lagou-cloud-hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone:
        http://zyz-eureka-server-1:8761/eureka/,http://zyz-eureka-server-2:8762/eureka/
      
#turbine配置
turbine:
  appConfig: zyz-service-autodeliver
  clusterNameExpression: "'default'" # 集群默认名称