server:
  port: 9003

spring:
  application:
    name: zyz-oauth-server

eureka:
    client:
      serviceUrl: # eureka server的路径
        defaultZone: http://zyz-eureka-server-1:8761/eureka/,http://zyz-eureka-server-2:8762/eureka
